import type { OpportunityRow } from './types'
import type { Opportunity } from '@/types/opportunity'

export function mapRowToOpportunity(row: OpportunityRow): Opportunity {
  return {
    id: row.id,
    slug: row.slug,
    name: row.name,
    pitch: row.pitch,
    originCountry: row.origin_country,
    originCountryCode: row.origin_country_code,
    originFlag: row.origin_flag,
    sector: row.sector as Opportunity['sector'],
    targetClient: row.target_client,
    clientType: row.client_type as Opportunity['clientType'],
    techComplexity: row.tech_complexity as Opportunity['techComplexity'],
    franceCompetition: row.france_competition as Opportunity['franceCompetition'],
    revenueMin: row.revenue_min,
    revenueMax: row.revenue_max,
    buildableUnder30Days: row.buildable_under_30_days,
    boringBusiness: row.boring_business,
    aiPowered: row.ai_powered,
    lowCompetition: row.low_competition,
    weeklyPick: row.weekly_pick,
    entrepreneursBuilding: row.entrepreneurs_building,
    foreignInspiration: row.foreign_inspiration,
    claudePrompt: row.claude_prompt,
    url: row.url ?? undefined,
    createdAt: row.created_at,
    publishedAt: row.published_at ?? undefined,
    scores: row.scores as unknown as Opportunity['scores'],
    franceFitCriteria: row.france_fit_criteria as unknown as Opportunity['franceFitCriteria'],
    tractionSignals: row.traction_signals as unknown as Opportunity['tractionSignals'],
    whyItWorks: row.why_it_works as unknown as Opportunity['whyItWorks'],
    franceAnalysis: row.france_analysis as string[],
    financialScenarios: row.financial_scenarios as unknown as Opportunity['financialScenarios'],
    cacChannels: row.cac_channels as unknown as Opportunity['cacChannels'],
    acquisition: row.acquisition as unknown as Opportunity['acquisition'],
    mvpPlan: row.mvp_plan as unknown as Opportunity['mvpPlan'],
    foreignMarketProfile: (row.foreign_market_profile as unknown as Opportunity['foreignMarketProfile']) ?? undefined,
    infraCosts: (row.infra_costs as unknown as Opportunity['infraCosts']) ?? undefined,
    frenchCompetitors: (row.french_competitors as unknown as Opportunity['frenchCompetitors']) ?? undefined,
    launchTimeline: (row.launch_timeline as unknown as Opportunity['launchTimeline']) ?? undefined,
    emailTemplates: (row.email_templates as unknown as Opportunity['emailTemplates']) ?? undefined,
    partnersFR: (row.partners_fr as unknown as Opportunity['partnersFR']) ?? undefined,
    roiInputs: (row.roi_inputs as unknown as Opportunity['roiInputs']) ?? undefined,
    tamBreakdown: (row.tam_breakdown as unknown as Opportunity['tamBreakdown']) ?? undefined,
    competitionAlerts: (row.competition_alerts as unknown as Opportunity['competitionAlerts']) ?? undefined,
  }
}

export function toOpportunityRow(opp: Opportunity): OpportunityRow {
  return {
    id: opp.id,
    slug: opp.slug,
    name: opp.name,
    pitch: opp.pitch,
    origin_country: opp.originCountry,
    origin_country_code: opp.originCountryCode,
    origin_flag: opp.originFlag,
    sector: opp.sector,
    target_client: opp.targetClient,
    client_type: opp.clientType,
    tech_complexity: opp.techComplexity,
    france_competition: opp.franceCompetition,
    revenue_min: opp.revenueMin,
    revenue_max: opp.revenueMax,
    buildable_under_30_days: opp.buildableUnder30Days,
    boring_business: opp.boringBusiness,
    ai_powered: opp.aiPowered,
    low_competition: opp.lowCompetition,
    weekly_pick: opp.weeklyPick ?? false,
    entrepreneurs_building: opp.entrepreneursBuilding,
    foreign_inspiration: opp.foreignInspiration,
    claude_prompt: opp.claudePrompt,
    url: opp.url ?? null,
    created_at: opp.createdAt,
    scores: opp.scores as unknown as Record<string, number>,
    france_fit_criteria: opp.franceFitCriteria as unknown as Record<string, unknown>,
    traction_signals: opp.tractionSignals,
    why_it_works: opp.whyItWorks,
    france_analysis: opp.franceAnalysis,
    financial_scenarios: opp.financialScenarios,
    cac_channels: opp.cacChannels,
    acquisition: opp.acquisition,
    mvp_plan: opp.mvpPlan as unknown as Record<string, unknown>,
    foreign_market_profile: (opp.foreignMarketProfile as unknown as Record<string, unknown>) ?? null,
    infra_costs: opp.infraCosts ?? null,
    french_competitors: opp.frenchCompetitors ?? null,
    launch_timeline: opp.launchTimeline ?? null,
    email_templates: opp.emailTemplates ?? null,
    partners_fr: opp.partnersFR ?? null,
    roi_inputs: opp.roiInputs ?? null,
    tam_breakdown: (opp.tamBreakdown as unknown as Record<string, unknown>) ?? null,
    competition_alerts: opp.competitionAlerts ?? null,
  }
}
